#https://www.cnblogs.com/babycomeon/p/11161073.html
server: 
  port: 9101
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9001
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #上面这段配置的意思是，配置了一个 id 为 my-first-gateway-route 的路由规则，当访问地址 http://localhost:8080/gateway-route-test时会自动转发到地址：https://www.baidu.com
        - id: my-first-gateway-route # 我们自定义的路由 ID，保持唯一
          uri: https://www.baidu.com #目标服务地址
          predicates: #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/gateway-route-test

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/