server:
  port: 9301
  
spring:
  application:
    name: order
  zipkin:
    base-url: http://localhost:9001
  sleuth:
    sampler:
      probability: 1.0
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
    
feign:
  hystrix:
    enabled: true

#http://localhost:9003/swagger-ui.html
swagger:
  base-package: org.sc
